import type { DirectoryListing } from "@/lib/directory/types";

/**
 * Brooklyn directory — REAL, address-verified listings (June 2026).
 * Generated by scripts/build-brooklyn-seed.mjs from
 * docs/brooklyn-directory-candidates.md. Addresses verified against GrowNYC,
 * NYC DOHMH, NYC Food Policy Center, and store sources. Coordinates geocoded
 * via OSM Nominatim. Farmers-market days/hours are accurate (GrowNYC); store
 * hours are typical/approximate — entries with verified:false still need their
 * hours/season confirmed. Re-run the script to regenerate.
 */
export const DIRECTORY_SEED: DirectoryListing[] = [
  {
    "id": "gm-grand-army",
    "name": "Grand Army Plaza Greenmarket",
    "address": "Prospect Park West & Flatbush Ave, Prospect Heights",
    "lat": 40.6749223,
    "lng": -73.9708155,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "16:00"
        }
      ]
    },
    "highlights": "Brooklyn's flagship greenmarket — regional farms, greens, fruit, eggs.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-boro-hall",
    "name": "Brooklyn Borough Hall Greenmarket",
    "address": "Court St & Montague St, Downtown Brooklyn",
    "lat": 40.6941,
    "lng": -73.991777,
    "category": "farmers_market",
    "hours": {
      "tue": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Downtown's year-round market — produce, bread, dairy from local farms.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "gm-fort-greene",
    "name": "Fort Greene Greenmarket",
    "address": "Washington Park btwn DeKalb & Willoughby Ave, Fort Greene",
    "lat": 40.6914756,
    "lng": -73.9756224,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Saturdays in Fort Greene Park — leafy greens, root veg, eggs.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "gm-cortelyou",
    "name": "Cortelyou Greenmarket",
    "address": "Cortelyou Rd btwn Argyle & Rugby Rd, Ditmas Park",
    "lat": 40.6403508,
    "lng": -73.9660298,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "14:00"
        }
      ]
    },
    "highlights": "Flatbush's Sunday market — seasonal produce and local growers.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "gm-carroll-gardens",
    "name": "Carroll Gardens Greenmarket",
    "address": "Carroll St btwn Smith & Court St, Carroll Gardens",
    "lat": 40.680303,
    "lng": -73.995048,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "14:00"
        }
      ]
    },
    "highlights": "Sunday produce by Carroll Park — fruit, vegetables, baked goods.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "gm-bartel-pritchard",
    "name": "Bartel-Pritchard Square Greenmarket",
    "address": "Prospect Park West & 15th St, Park Slope",
    "lat": 40.660999,
    "lng": -73.9798675,
    "category": "farmers_market",
    "hours": {
      "wed": [
        {
          "open": "08:00",
          "close": "14:00"
        }
      ],
      "sun": [
        {
          "open": "09:00",
          "close": "14:00"
        }
      ]
    },
    "highlights": "Park Slope greenmarket at the Prospect Park entrance.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-7th-sunset",
    "name": "7th Ave Sunset Park Greenmarket",
    "address": "7th Ave & 44th St, Sunset Park",
    "lat": 40.6456081,
    "lng": -74.0024849,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Year-round Sunset Park market — affordable fresh produce.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "gm-bay-ridge",
    "name": "Bay Ridge Greenmarket",
    "address": "3rd Ave & 95th St, Bay Ridge",
    "lat": 40.6170101,
    "lng": -74.0338142,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Seasonal Saturday market with regional farm produce.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-bensonhurst",
    "name": "Bensonhurst Greenmarket",
    "address": "18th Ave btwn 81st & 82nd St (Milestone Park), Bensonhurst",
    "lat": 40.6101604,
    "lng": -73.9991388,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "09:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Sundays at Milestone Park — seasonal fruit and vegetables.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-borough-park",
    "name": "Borough Park Greenmarket",
    "address": "14th Ave btwn 49th & 50th St, Borough Park",
    "lat": 40.6338915,
    "lng": -73.9900985,
    "category": "farmers_market",
    "hours": {
      "thu": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Seasonal Thursday market with local farm produce.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": false
  },
  {
    "id": "gm-domino",
    "name": "Domino Park Greenmarket",
    "address": "River St btwn S 3rd & S 4th St, Williamsburg",
    "lat": 40.7141055,
    "lng": -73.9682746,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Waterfront Williamsburg market — seasonal local produce.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-mccarren",
    "name": "McCarren Park Greenmarket",
    "address": "Union Ave btwn Driggs Ave & N 12th St, Williamsburg",
    "lat": 40.7211592,
    "lng": -73.9528793,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Year-round Saturday market on the Williamsburg/Greenpoint line.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "gm-mcgolrick",
    "name": "McGolrick Park Down to Earth Market",
    "address": "108 Russell St (in McGolrick Park), Greenpoint",
    "lat": 40.7242845,
    "lng": -73.9443879,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "09:00",
          "close": "14:00"
        }
      ]
    },
    "highlights": "Greenpoint Sunday market — produce, bread, local goods.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-park-slope-d2e",
    "name": "Park Slope Down to Earth Market",
    "address": "289 4th St (Old Stone House), Park Slope",
    "lat": 40.6724317,
    "lng": -73.9840876,
    "category": "farmers_market",
    "hours": {
      "sun": [
        {
          "open": "09:00",
          "close": "14:00"
        }
      ]
    },
    "highlights": "Sundays at the Old Stone House — seasonal local produce.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": true
  },
  {
    "id": "gm-bed-stuy-farmstand",
    "name": "Bed-Stuy Farmstand (GrowNYC)",
    "address": "Decatur St & Lewis Ave, Bedford-Stuyvesant",
    "lat": 40.6814842,
    "lng": -73.9348957,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "09:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "GrowNYC youth-run farmstand bringing fresh produce to Bed-Stuy.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal",
      "ebt-snap"
    ],
    "verified": false
  },
  {
    "id": "gm-4th-sunset",
    "name": "4th Ave Sunset Park Greenmarket",
    "address": "4th Ave near 44th St, Sunset Park",
    "lat": 40.6499189,
    "lng": -74.0094736,
    "category": "farmers_market",
    "hours": {
      "sat": [
        {
          "open": "08:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Seasonal Saturday produce market in Sunset Park.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": false
  },
  {
    "id": "hf-ps-food-coop",
    "name": "Park Slope Food Coop",
    "address": "782 Union St, Brooklyn, NY 11215",
    "lat": 40.6747295,
    "lng": -73.976815,
    "category": "health_food_store",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Member co-op with huge fresh & organic produce at low markups.",
    "tags": [
      "fresh-produce",
      "organic",
      "bulk",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "hf-flatbush-coop",
    "name": "Flatbush Food Coop",
    "address": "1415 Cortelyou Rd, Brooklyn, NY 11226",
    "lat": 40.6413211,
    "lng": -73.9647365,
    "category": "health_food_store",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Open-to-all co-op — organic produce, bulk goods, supplements.",
    "tags": [
      "fresh-produce",
      "organic",
      "bulk"
    ],
    "verified": true
  },
  {
    "id": "hf-natural-frontier",
    "name": "Natural Frontier Market",
    "address": "1102 Cortelyou Rd, Brooklyn, NY 11218",
    "lat": 40.6395581,
    "lng": -73.9677416,
    "category": "health_food_store",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Full natural market — organic produce, juice bar, supplements.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-sunac",
    "name": "Sunac Natural Market",
    "address": "440 Union Ave, Brooklyn, NY 11211",
    "lat": 40.7136512,
    "lng": -73.9512221,
    "category": "health_food_store",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "23:00"
        }
      ]
    },
    "highlights": "Daily-fresh local produce, juices, and a salad bar.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-greene-grape",
    "name": "Greene Grape Provisions",
    "address": "767 Fulton St, Brooklyn, NY 11217",
    "lat": 40.6863223,
    "lng": -73.9739262,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Fort Greene grocer with excellent produce, butcher, and cheese.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-union-ps",
    "name": "Union Market (Park Slope)",
    "address": "402 7th Ave, Brooklyn, NY 11215",
    "lat": 40.6648047,
    "lng": -73.9836187,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Gourmet grocer — strong produce, cheese, meats, prepared foods.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-union-cobble",
    "name": "Union Market (Cobble Hill)",
    "address": "288 Court St, Brooklyn, NY 11231",
    "lat": 40.6843504,
    "lng": -73.9952561,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Gourmet grocer with fresh produce and prepared foods.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-mom-pop",
    "name": "Mom & Pop's Organic Market",
    "address": "889 Manhattan Ave, Brooklyn, NY 11222",
    "lat": 40.7299039,
    "lng": -73.9543918,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "mon": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "tue": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "wed": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "thu": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "fri": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ],
      "sat": [
        {
          "open": "00:00",
          "close": "23:59"
        }
      ]
    },
    "highlights": "24-hour Greenpoint grocer with organic produce deals.",
    "tags": [
      "fresh-produce",
      "organic"
    ],
    "verified": true
  },
  {
    "id": "hf-tonys",
    "name": "Tony's Health Food",
    "address": "2923 Glenwood Rd, Brooklyn, NY 11210",
    "lat": 40.6341135,
    "lng": -73.9479747,
    "category": "health_food_store",
    "hours": {
      "mon": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ],
      "tue": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ],
      "wed": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ],
      "thu": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ],
      "fri": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ],
      "sat": [
        {
          "open": "09:00",
          "close": "19:00"
        }
      ]
    },
    "highlights": "Long-running natural supplement & herb shop (lighter on produce).",
    "tags": [
      "organic"
    ],
    "verified": true
  },
  {
    "id": "cm-labay",
    "name": "LABAY Market",
    "address": "1127 Nostrand Ave, Brooklyn, NY 11225",
    "lat": 40.6602393,
    "lng": -73.9503898,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Black-owned Caribbean grocer — soursop, tropical fruit, callaloo, ground provisions.",
    "tags": [
      "fresh-produce",
      "caribbean",
      "black-owned"
    ],
    "verified": true
  },
  {
    "id": "cm-caribbean-supermarket",
    "name": "Caribbean Supermarket",
    "address": "741 Utica Ave, Brooklyn, NY 11203",
    "lat": 40.6548333,
    "lng": -73.9303516,
    "category": "grocer",
    "hours": {
      "mon": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sun": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ]
    },
    "highlights": "West Indian & Jamaican staples plus fresh produce.",
    "tags": [
      "fresh-produce",
      "caribbean",
      "jamaican"
    ],
    "verified": true
  },
  {
    "id": "cm-food-garden",
    "name": "Food Garden Market",
    "address": "608 Franklin Ave, Brooklyn, NY 11238",
    "lat": 40.6778726,
    "lng": -73.9554792,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Crown Heights grocer — full produce, butcher, fish, juice bar, bakery.",
    "tags": [
      "fresh-produce",
      "organic",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-flatbush-central",
    "name": "Flatbush Central Caribbean Marketplace",
    "address": "2123 Caton Ave, Brooklyn, NY 11226",
    "lat": 40.6529225,
    "lng": -73.9599165,
    "category": "market",
    "hours": {
      "mon": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ],
      "tue": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ],
      "wed": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ],
      "thu": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ],
      "fri": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ],
      "sat": [
        {
          "open": "10:00",
          "close": "20:00"
        }
      ]
    },
    "highlights": "Caribbean vendor marketplace; in-season Wednesday farmers' market.",
    "tags": [
      "fresh-produce",
      "caribbean"
    ],
    "verified": true
  },
  {
    "id": "cm-food-universe-369",
    "name": "Food Universe Marketplace",
    "address": "369 Flatbush Ave, Brooklyn, NY 11238",
    "lat": 40.6767227,
    "lng": -73.9716703,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Neighborhood supermarket — produce, meat, grocery staples.",
    "tags": [
      "fresh-produce",
      "affordable",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-ctown-church",
    "name": "CTown Supermarket (Church Ave)",
    "address": "5311 Church Ave, Brooklyn, NY 11203",
    "lat": 40.652639,
    "lng": -73.9270425,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Affordable full grocery with produce; accepts SNAP.",
    "tags": [
      "fresh-produce",
      "affordable",
      "caribbean",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-ideal-food-basket",
    "name": "Ideal Food Basket",
    "address": "4806 Church Ave, Brooklyn, NY 11203",
    "lat": 40.6514419,
    "lng": -73.9319786,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Affordable supermarket — strong produce; SNAP/WIC.",
    "tags": [
      "fresh-produce",
      "affordable",
      "caribbean",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-met-foods",
    "name": "Met Foodmarket",
    "address": "1086 Brooklyn Ave, Brooklyn, NY 11203",
    "lat": 40.6474129,
    "lng": -73.9437307,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "East Flatbush supermarket with fresh produce.",
    "tags": [
      "fresh-produce",
      "affordable",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-songs-fruit",
    "name": "Song's Fruit Market",
    "address": "848 Utica Ave, Brooklyn, NY 11203",
    "lat": 40.6523835,
    "lng": -73.9308133,
    "category": "market",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Dedicated fruit & produce market on Utica Ave.",
    "tags": [
      "fresh-produce",
      "produce-specialist",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-new-best-utica",
    "name": "New Best Utica Market",
    "address": "890 Utica Ave, Brooklyn, NY 11203",
    "lat": 40.6513235,
    "lng": -73.9306825,
    "category": "market",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Produce-focused market on Utica Ave.",
    "tags": [
      "fresh-produce",
      "produce-specialist",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-mr-mango",
    "name": "Mr. Mango Fruit & Vegetables",
    "address": "112 Rockaway Ave, Brooklyn, NY 11233",
    "lat": 40.6796254,
    "lng": -73.9112562,
    "category": "market",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "20:00"
        }
      ]
    },
    "highlights": "Beloved Brownsville green-grocer — lots of affordable fresh produce.",
    "tags": [
      "fresh-produce",
      "produce-specialist",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-super-foodtown-bedstuy",
    "name": "Super Foodtown of Bed-Stuy",
    "address": "1420 Fulton St, Brooklyn, NY 11216",
    "lat": 40.68002,
    "lng": -73.944554,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "mon": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "tue": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "wed": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "thu": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "fri": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ],
      "sat": [
        {
          "open": "07:00",
          "close": "22:00"
        }
      ]
    },
    "highlights": "Full supermarket — organic produce plus Caribbean & soul-food selections.",
    "tags": [
      "fresh-produce",
      "soul-food",
      "caribbean",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-fei-long",
    "name": "Fei Long Supermarket",
    "address": "6301 8th Ave, Brooklyn, NY 11220",
    "lat": 40.6332386,
    "lng": -74.0111558,
    "category": "grocer",
    "hours": {
      "sun": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "mon": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "21:00"
        }
      ]
    },
    "highlights": "Large Sunset Park market — very affordable produce, seafood, meat; EBT.",
    "tags": [
      "fresh-produce",
      "asian",
      "affordable",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-meat-place",
    "name": "The Meat Place",
    "address": "1889 Nostrand Ave, Brooklyn, NY 11226",
    "lat": 40.6395786,
    "lng": -73.9482615,
    "category": "grocer",
    "hours": {
      "mon": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ]
    },
    "highlights": "Butcher/grocer on the Little Caribbean corridor; SNAP.",
    "tags": [
      "caribbean",
      "affordable",
      "ebt-snap"
    ],
    "verified": true
  },
  {
    "id": "cm-green-village-meat",
    "name": "Green Village Meat Market",
    "address": "1861 Nostrand Ave, Brooklyn, NY 11226",
    "lat": 40.6403557,
    "lng": -73.9481749,
    "category": "grocer",
    "hours": {
      "mon": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "tue": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "wed": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "thu": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "fri": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ],
      "sat": [
        {
          "open": "08:00",
          "close": "20:00"
        }
      ]
    },
    "highlights": "Meat market & grocer on the Nostrand Ave Caribbean corridor.",
    "tags": [
      "caribbean",
      "affordable"
    ],
    "verified": true
  },
  {
    "id": "cm-bk-grange",
    "name": "Brooklyn Grange Farm Stand",
    "address": "Brooklyn Army Terminal, 140 58th St, Sunset Park, NY 11220",
    "lat": 40.6450576,
    "lng": -74.0254948,
    "category": "market",
    "hours": {
      "sun": [
        {
          "open": "10:00",
          "close": "15:00"
        }
      ]
    },
    "highlights": "Rooftop-farm produce stand — ultra-fresh local vegetables, in season.",
    "tags": [
      "fresh-produce",
      "local-farms",
      "seasonal"
    ],
    "verified": false
  }
];
